#!/usr/bin/env python3

import logging
import argparse

from JDIN import config
from JDIN import logger
from JDIN.OAMAlarm import AlarmTester

trace = logger.init_logger()

def main ():
    parser = argparse.ArgumentParser()
    parser.add_argument('fname', nargs='?',
                        type=str, help='test case file');
    args = parser.parse_args()

    if not args.fname:
        parser.print_help()
        parser.exit()

    tester = AlarmTester ()
    tester.run('192.168.0.170', 8990, args.fname)

if __name__ == '__main__':
    main ()
